In [1]:
pip install torch

Note: you may need to restart the kernel to use updated packages.


In [2]:
import torch

#### Scaler

In [3]:
t1 = torch.tensor(4)

In [4]:
t1

tensor(4)

In [5]:
t2 = torch.tensor(6.7)

In [6]:
t2

tensor(6.7000)

In [7]:
t2.dtype

torch.float32

#### Metrics

In [8]:
t3 = torch.tensor([[3,6], [10,16], [9,20]])

In [9]:
t3

tensor([[ 3,  6],
        [10, 16],
        [ 9, 20]])

In [10]:
## Checking the number of rows and columns in metrix 't3'
t3.shape

torch.Size([3, 2])

In [11]:
## Checking the shape for a three dimensional tenor 
t4 = torch.tensor([[[3,6], [10,16], [23,34]], [[34,67], [9,20], [9,13]]])

In [12]:
t4

tensor([[[ 3,  6],
         [10, 16],
         [23, 34]],

        [[34, 67],
         [ 9, 20],
         [ 9, 13]]])

In [13]:
t4.shape

torch.Size([2, 3, 2])

In [14]:
t1.shape ## For a scaler tensor there will be no shape

torch.Size([])

#### Tensor Operatrions and Gradients

In [15]:
x = torch.tensor(8)
w = torch.tensor(5.0, requires_grad=True) ## later we would be differentiating a function with respect to this variable
b = torch.tensor(4.0, requires_grad=True) ## later we would be differentiating a function with respect to this variable

Our parametric function is : y = w*x + b ; where w and b are the parameters. Now we can use the '.backward' method in order to calculate the partial derivatives dy/dw and dy/db. We can calculate the derivative of y with respect to the tensors w and b because those tensors have 'requires_grad' set to true. 

In [16]:
y = w*x + b ## function

In [17]:
## Computing derivatives
y.backward()

In [18]:
print('dy/dx =', x.grad)
print('dy/dw =', w.grad)
print('dy/db =', b.grad)

dy/dx = None
dy/dw = tensor(8.)
dy/db = tensor(1.)


In [19]:
## Creating metrix with same elements
t5 = torch.full((3,2), 28)

In [20]:
t5

tensor([[28, 28],
        [28, 28],
        [28, 28]])

In [21]:
t3

tensor([[ 3,  6],
        [10, 16],
        [ 9, 20]])

In [22]:
## Concatinating metrices
t6 = torch.cat((t3,t5))

In [23]:
t6

tensor([[ 3,  6],
        [10, 16],
        [ 9, 20],
        [28, 28],
        [28, 28],
        [28, 28]])

In [24]:
## Computing sin and cos of all the elemnts of t3
t7 = torch.sin(t3)
t8 = torch.cos(t3)

In [25]:
t7

tensor([[ 0.1411, -0.2794],
        [-0.5440, -0.2879],
        [ 0.4121,  0.9129]])

In [26]:
t8

tensor([[-0.9900,  0.9602],
        [-0.8391, -0.9577],
        [-0.9111,  0.4081]])

In [27]:
## Reshaping a metrix
t9 = t6.reshape(4,3)

In [28]:
t9

tensor([[ 3,  6, 10],
        [16,  9, 20],
        [28, 28, 28],
        [28, 28, 28]])

In [29]:
t10 = t4.reshape(3,2,2)

In [30]:
t10

tensor([[[ 3,  6],
         [10, 16]],

        [[23, 34],
         [34, 67]],

        [[ 9, 20],
         [ 9, 13]]])

#### Interoperability of pytorch with numpy

In [31]:
import numpy as np
t11 = np.array([[34,56,11], [90,56,72], [21,41,12]])

In [32]:
t12 = torch.from_numpy(t11)

In [33]:
t12

tensor([[34, 56, 11],
        [90, 56, 72],
        [21, 41, 12]])

In [34]:
## Checking the datatype both numpy array and torch tensor 
print(t11.dtype)
print(t12.dtype)

int64
torch.int64


Hence both are having the same datatype.

In [35]:
t13 = t12.numpy()

In [36]:
t13

array([[34, 56, 11],
       [90, 56, 72],
       [21, 41, 12]])

So we can convert a numpy variable to a torch tensor and we can convert a torch tensor back to numpy.

#### Linear regression using Pytorch

In [114]:
## Making the training data
## The input features are : (temperature, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [115]:
inputs ## The row are the observations and the columns are the features mentioned 

array([[ 73.,  67.,  43.],
       [ 91.,  88.,  64.],
       [ 87., 134.,  58.],
       [102.,  43.,  37.],
       [ 69.,  96.,  70.]], dtype=float32)

In [116]:
##### The target is the number of (apples and oranges) the are sold 
target = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [117]:
target

array([[ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.]], dtype=float32)

In [118]:
inputs = torch.from_numpy(inputs)
target = torch.from_numpy(target)

In [119]:
print('inputs:', '\n', inputs, '\n')
print('target:', '\n', target)

inputs: 
 tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]]) 

target: 
 tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [120]:
## Weights and biases
w = torch.randn(2,3, requires_grad = True) ## one set of three weights are for apples and one set of three weights are for oranges
b = torch.randn(2, requires_grad = True) ## one bias is for apples and one bias is for oranges

In [121]:
print('weights:', '\n', w, '\n')
print('biases:', '\n', b)

weights: 
 tensor([[-1.2105,  1.5428, -0.2436],
        [-0.6959,  1.2338, -0.0758]], requires_grad=True) 

biases: 
 tensor([-0.1869, -0.7026], requires_grad=True)


In [122]:
## Model
def model(x):  
    return x @ w.t() + b ## Taking the transpose of 'w' before calculating the dot product

In [123]:
## Prediction 
pred = model(inputs)
print('prediction:', '\n', pred)

prediction: 
 tensor([[  4.3382,  27.9001],
        [  9.8319,  39.6911],
        [ 87.1021,  99.6830],
        [-66.3303, -21.4362],
        [ 47.3430,  64.4158]], grad_fn=<AddBackward0>)


In [124]:
## Loss function: MSE
def MSE(actual, predicted):
    diff = actual-predicted
    return torch.sum(diff**2)/diff.numel() ## numel stands for number of elements in a tensor

In [125]:
loss = MSE(target, pred)
print(loss)

tensor(3268.6699, grad_fn=<DivBackward0>)


In [126]:
## Model Training

for i in range(400):     ## we would do 200 iterations
    preds = model(inputs)
    loss = MSE(target, preds)
    loss.backward()
    
    with torch.no_grad():
        w -= w.grad * 1e-5   ## weight updation rule in gradient discent
        b -= b.grad * 1e-5
        w.grad.zero_()       ## resetting the weights to zero before recalculating for the next epoch
        b.grad.zero_()
    
    print('Epoch ', i, ':', 'Loss =', loss)

Epoch  0 : Loss = tensor(3268.6699, grad_fn=<DivBackward0>)
Epoch  1 : Loss = tensor(2353.7983, grad_fn=<DivBackward0>)
Epoch  2 : Loss = tensor(1735.6650, grad_fn=<DivBackward0>)
Epoch  3 : Loss = tensor(1317.5183, grad_fn=<DivBackward0>)
Epoch  4 : Loss = tensor(1034.1597, grad_fn=<DivBackward0>)
Epoch  5 : Loss = tensor(841.6522, grad_fn=<DivBackward0>)
Epoch  6 : Loss = tensor(710.3871, grad_fn=<DivBackward0>)
Epoch  7 : Loss = tensor(620.4112, grad_fn=<DivBackward0>)
Epoch  8 : Loss = tensor(558.2781, grad_fn=<DivBackward0>)
Epoch  9 : Loss = tensor(514.9259, grad_fn=<DivBackward0>)
Epoch  10 : Loss = tensor(484.2484, grad_fn=<DivBackward0>)
Epoch  11 : Loss = tensor(462.1304, grad_fn=<DivBackward0>)
Epoch  12 : Loss = tensor(445.7978, grad_fn=<DivBackward0>)
Epoch  13 : Loss = tensor(433.3817, grad_fn=<DivBackward0>)
Epoch  14 : Loss = tensor(423.6218, grad_fn=<DivBackward0>)
Epoch  15 : Loss = tensor(415.6693, grad_fn=<DivBackward0>)
Epoch  16 : Loss = tensor(408.9515, grad_fn=<

So we can see that the loss has gradually reduced.

In [128]:
preds = model(inputs)
loss = MSE(target, preds)
print(loss)

tensor(42.4226, grad_fn=<DivBackward0>)


In [131]:
## Final prediction for apples and oranges
preds

tensor([[ 57.0331,  70.4182],
        [ 77.4344,  95.9405],
        [129.7590, 143.5375],
        [ 20.0156,  37.8427],
        [ 94.2047, 110.2897]], grad_fn=<AddBackward0>)

In [132]:
target

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

So we can observe that our predictions are quite close to our actual.