## TensorFlow Fundamentals

In [1]:
pip install tensorflow

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 489.8/489.8 MB 3.2 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 22.9/22.9 MB 51.6 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.5/65.5 kB 11.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 64.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 440.7/440.7 kB 48.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 kB 10.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.3/5.3 MB 70.9 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.9/77.9 kB 14.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 69.5 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 70.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 130.2/130.2 kB 22.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 62.8 MB/s eta 0:00:0

In [3]:
import tensorflow as tf

2023-10-10 11:46:42.083702: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-10-10 11:46:42.148709: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-10-10 11:46:42.148777: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-10-10 11:46:42.148820: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-10-10 11:46:42.159232: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-10-10 11:46:42.160096: I tensorflow/core/platform/cpu_feature_guard.cc:182] This Tens

#### Tensor Constants

In [107]:
constant = tf.constant(42)

In [108]:
constant

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [109]:
constant.numpy()

42

In [110]:
string = tf.constant('Data Science')

In [111]:
string

<tf.Tensor: shape=(), dtype=string, numpy=b'Data Science'>

In [112]:
string.numpy()

b'Data Science'

In [113]:
string = tf.constant(True, dtype=tf.bool)

In [114]:
string = tf.constant('34', dtype=tf.string)

In [115]:
string

<tf.Tensor: shape=(), dtype=string, numpy=b'34'>

In [116]:
string.numpy()

b'34'

In [117]:
metrix = tf.constant([[4,6], [7,2]])

In [118]:
metrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 6],
       [7, 2]], dtype=int32)>

In [119]:
metrix.numpy()

array([[4, 6],
       [7, 2]], dtype=int32)

In [120]:
metrix.shape

TensorShape([2, 2])

In [121]:
metrix.dtype

tf.int32

In [122]:
print(tf.ones(shape=(3,5)))

tf.Tensor(
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]], shape=(3, 5), dtype=float32)


In [123]:
ones = tf.ones(shape=(3,5))

In [124]:
ones

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [125]:
tf.zeros(shape=(6,3))

<tf.Tensor: shape=(6, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [126]:
mtx1 = tf.constant([[5,7,3], [7,3,1]])
mtx2 = tf.constant([[2,6,4], [8,3,7]])

In [127]:
result = tf.add(mtx1, mtx2)

In [128]:
result

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7, 13,  7],
       [15,  6,  8]], dtype=int32)>

#### Random Constant

In [129]:
dist = tf.random.normal(shape=(3,3),mean=7, stddev=5)

In [130]:
dist

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[12.79003   ,  5.700716  ,  4.0077515 ],
       [ 4.0848083 , 16.48298   , 13.603188  ],
       [-0.40831375,  8.400764  ,  8.01189   ]], dtype=float32)>

In [131]:
norm = tf.random.uniform(shape=(3,3), minval=3, maxval=45)

In [132]:
norm

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[31.155334 , 36.39885  , 28.159016 ],
       [30.434868 ,  7.0749264,  7.5765667],
       [26.341982 , 36.40993  , 10.814013 ]], dtype=float32)>

#### Tensor Variables

In [133]:
var1 = tf.Variable(34)

In [134]:
var1.numpy()

34

In [135]:
var1 = 8

In [136]:
var1

8

In [137]:
tf.Variable([[[2,4,5], [7,5,6], [3,8,3]], [[2,4,5], [7,5,6], [3,8,3]]])

<tf.Variable 'Variable:0' shape=(2, 3, 3) dtype=int32, numpy=
array([[[2, 4, 5],
        [7, 5, 6],
        [3, 8, 3]],

       [[2, 4, 5],
        [7, 5, 6],
        [3, 8, 3]]], dtype=int32)>

Variables can be assigned a new value but not constants cannot be assigned any new values

In [138]:
con = tf.constant(42)

In [139]:
con.numpy()

42

In [140]:
var = tf.Variable(34)

In [141]:
var.numpy()

34

In [142]:
var.assign(89)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=89>

In [143]:
var.numpy()

89

In [144]:
constant.assign(34)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [ ]:
mtx = tf.Variable([[8,6,7], [4,5,8]]) 

In [145]:
mtx.numpy()

array([[8, 3, 6],
       [9, 3, 6]], dtype=int32)

In [146]:
## Assigning new values to a metrix
mtx.assign([[8,3,6], [9,3,6]])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[8, 3, 6],
       [9, 3, 6]], dtype=int32)>

In [147]:
mtx

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[8, 3, 6],
       [9, 3, 6]], dtype=int32)>

In [148]:
mtx1 = tf.Variable([[6,8,2], [5,7,8]]) 

In [149]:
mtx1

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[6, 8, 2],
       [5, 7, 8]], dtype=int32)>

In [150]:
## Adding mtx to mtx1 and making a new metrix mtx2 : The values of the corresponding indexes of the two metrices gets added
mtx2 = mtx.assign_add(mtx1)

In [151]:
mtx2

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[14, 11,  8],
       [14, 10, 14]], dtype=int32)>

In [152]:
## Subtracting mtx1 to mtx and making a new metrix mtx3 : The difference beyween the values of the corresponding indexes gets calculated 
mtx3 = mtx.assign_sub(mtx1)

In [153]:
mtx3

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[8, 3, 6],
       [9, 3, 6]], dtype=int32)>

In [154]:
## Checking the number of rows and columns that is the dimension of a metrix
mtx.shape

TensorShape([2, 3])

In [155]:
## Changing the dimension of a metrix
mtx4 = tf.reshape(mtx,[1,6])

In [156]:
mtx4

<tf.Tensor: shape=(1, 6), dtype=int32, numpy=array([[8, 3, 6, 9, 3, 6]], dtype=int32)>

In [157]:
mtx

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[8, 3, 6],
       [9, 3, 6]], dtype=int32)>

In [158]:
## Checking the rank that is the number of dimensions of a metrix
print(tf.rank(mtx))

tf.Tensor(2, shape=(), dtype=int32)


In [159]:
big = tf.Variable([[[2,4,5], [7,5,6], [3,8,3]], [[5,7,2], [9,0,1], [4,9,2]]])

In [160]:
big

<tf.Variable 'Variable:0' shape=(2, 3, 3) dtype=int32, numpy=
array([[[2, 4, 5],
        [7, 5, 6],
        [3, 8, 3]],

       [[5, 7, 2],
        [9, 0, 1],
        [4, 9, 2]]], dtype=int32)>

In [161]:
print(tf.rank(big))

tf.Tensor(3, shape=(), dtype=int32)


In [162]:
## Slicing operation
big[0,0,1]

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [163]:
big[1,0,1]

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [164]:
## Checking the size of a metrix that is the total number of elements in a metrix 
tf.size(mtx)

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [165]:
mtx

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[8, 3, 6],
       [9, 3, 6]], dtype=int32)>

In [166]:
mtx1

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[6, 8, 2],
       [5, 7, 8]], dtype=int32)>

#### Mathematical Operations of two metrices

In [167]:
## Addition operation: The values of the corresponding indices are getting added 
mtx5 = mtx + mtx1

In [168]:
mtx5

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[14, 11,  8],
       [14, 10, 14]], dtype=int32)>

In [169]:
## Subtraction opeartion
mtx6 = mtx - mtx1

In [170]:
mtx6

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 2, -5,  4],
       [ 4, -4, -2]], dtype=int32)>

In [171]:
## Squaring each element of a metrix and making a new metrix
mtx7 = tf.square(mtx)

In [172]:
mtx7

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[64,  9, 36],
       [81,  9, 36]], dtype=int32)>

In [173]:
## Multiplication operation of two metrices : The values of the corresponding indices are getting multiplied
mtx8 = mtx*mtx1

In [174]:
mtx8

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[48, 24, 12],
       [45, 21, 48]], dtype=int32)>

#### Broadcating

In [175]:
mtx9 = mtx-4

In [176]:
mtx9

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 4, -1,  2],
       [ 5, -1,  2]], dtype=int32)>

#### Dot product of two metrices 

In [177]:
mtx10 = tf.transpose(mtx1)

In [178]:
tf.matmul(mtx, mtx10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 84, 109],
       [ 90, 114]], dtype=int32)>

#### Casting

In [179]:
mtx.dtype

tf.int32

In [180]:
## Changing the datatype of metrix 'mtx' from int32 to int64 
tf.cast(mtx, dtype=tf.int64)

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[8, 3, 6],
       [9, 3, 6]])>

In [181]:
## Ragged constant allows us to create a non rectrangular metrics
tf.ragged.constant([[1,2,3], [6]])

<tf.RaggedTensor [[1, 2, 3], [6]]>

In [182]:
## Squaring each element of the metrices and then taking the differences of those squared values index wise
tf.math.squared_difference(mtx, mtx1)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 4, 25, 16],
       [16, 16,  4]], dtype=int32)>

In [183]:
## Calculating the mean of an entire metrix
tf.reduce_mean(mtx)

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [184]:
## Calculating the mimimum value of an entire metrix
tf.reduce_min(mtx)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [185]:
## Calculating the mimimum value row wise
tf.reduce_min(mtx, axis=0)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([8, 3, 6], dtype=int32)>

In [186]:
## Calculating the minimum value column wise
tf.reduce_min(mtx, axis=1)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 3], dtype=int32)>

In [187]:
big

<tf.Variable 'Variable:0' shape=(2, 3, 3) dtype=int32, numpy=
array([[[2, 4, 5],
        [7, 5, 6],
        [3, 8, 3]],

       [[5, 7, 2],
        [9, 0, 1],
        [4, 9, 2]]], dtype=int32)>

In [188]:
## Taking the mean of the enire metrix column wise still maintaining the dimension
tf.reduce_mean(big, axis=1, keepdims=True)

<tf.Tensor: shape=(2, 1, 3), dtype=int32, numpy=
array([[[4, 5, 4]],

       [[6, 5, 1]]], dtype=int32)>

#### Setting the seed 

In [189]:
## Setting a seed value helps us to keep a set of values intact even after frequent iterations
tf.random.set_seed(11)
tf.random.uniform(shape=[2,4])

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[0.25061703, 0.8159225 , 0.29261577, 0.9327979 ],
       [0.76441216, 0.14772058, 0.33168125, 0.00725472]], dtype=float32)>

#### Concatination of metrices

In [190]:
dice1 = tf.random.uniform(shape=(10,1), minval=1, maxval=9)
dice2 = tf.random.uniform(shape=(10,1), minval=3, maxval=10)
dice3 = dice1+dice2

In [191]:
tf.concat(values=[dice1, dice2, dice3], axis=1)

<tf.Tensor: shape=(10, 3), dtype=float32, numpy=
array([[ 5.466031 ,  5.6238136, 11.089845 ],
       [ 1.4325666,  3.6858559,  5.1184225],
       [ 1.7517538,  7.1249943,  8.876748 ],
       [ 6.5324936,  3.4212713,  9.953765 ],
       [ 1.2239761,  7.8001432,  9.024119 ],
       [ 2.6995668,  9.498018 , 12.197585 ],
       [ 1.7427073,  7.845787 ,  9.588494 ],
       [ 3.9733286,  6.7660017, 10.73933  ],
       [ 8.667832 ,  6.0506506, 14.718483 ],
       [ 5.3797016,  3.8733735,  9.253075 ]], dtype=float32)>

#### Checking the argument(or index) of the maximum or minimum value of an array

In [192]:
tensor = tf.constant([4,6,2,9,5])

In [193]:
tensor

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([4, 6, 2, 9, 5], dtype=int32)>

In [194]:
i = tf.argmax(tensor)
print(i)
print(tensor[i].numpy)

tf.Tensor(3, shape=(), dtype=int64)
<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(), dtype=int32, numpy=9>>


In [195]:
i = tf.argmin(tensor)
print(i)
print(tensor[i].numpy)

tf.Tensor(2, shape=(), dtype=int64)
<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(), dtype=int32, numpy=2>>


In [196]:
mtx

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[8, 3, 6],
       [9, 3, 6]], dtype=int32)>

In [197]:
## Checking argmax column wise
i = tf.argmax(mtx, axis=1)
print(i)

tf.Tensor([0 0], shape=(2,), dtype=int64)


In [198]:
## Checking argmax row wise
i = tf.argmax(mtx, axis=0)
print(i)

tf.Tensor([1 0 0], shape=(3,), dtype=int64)


#### Tensor Function

In [199]:
def tensor(x1, x2):
    return tf.subtract(x1**3, x2**2)

In [200]:
tensor(45,78).numpy()

85041

In [201]:
def tensor1(x1, x2, x3):
    return tf.add(x1, x2**2, x3/2)

In [202]:
tensor1(234, 45, 88).numpy()

2259

In [203]:
def tensor1(x1, x2):
    return tf.reduce_mean(tf.multiply(x1**2, 8) + x2*5)

In [204]:
tensor1(tf.constant([4,5]), tf.constant([8,9])).numpy()

206